=== MrPaul98/BigJavaCodeSolution/Chapter26_kiv/RectangleMessageDTD/drawing.dtd
<!ELEMENT drawing (rectangle*, line*, message*)>
<!ELEMENT rectangle (x, y, width, height)>
<!ELEMENT line (x1, y1, x2, y2)>
<!ELEMENT message (text, x, y)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT x1 (#PCDATA)>
<!ELEMENT y1 (#PCDATA)>
<!ELEMENT x2 (#PCDATA)>
<!ELEMENT y2 (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT text (#PCDATA)>

=== MrPaul98/BigJavaCodeSolution/Chapter26_kiv/RectangleMessageDTD/drawing.xml
<?xml version="1.0"?>
<!DOCTYPE drawing SYSTEM "drawing.dtd">
<drawing>
	<rectangle>
		<x>5</x>
		<y>10</y>
		<width>20</width>
		<height>30</height>
	</rectangle>
	<line>
		<x1>5</x1>
		<y1>10</y1>
		<x2>25</x2>
		<y2>40</y2>
	</line>
	<message>
		<text>Hello, World!</text>
		<x>20</x>
		<y>30</y>
	</message>
</drawing>
